/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pastelaria;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.Position;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Andrea Silva
 */
public class Pastel extends javax.swing.JFrame {
DecimalFormat ft= new DecimalFormat("#,##0.00€");
    DecimalFormat ft1= new DecimalFormat("#,##0.00");
    
    float total=0;
    DefaultListModel lista1=new DefaultListModel();
    DefaultListModel lista2=new DefaultListModel();
    DefaultListModel lista3=new DefaultListModel();
    DefaultListModel lista4=new DefaultListModel();
    public Pastel() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btncafe = new javax.swing.JButton();
        btndecaf = new javax.swing.JButton();
        btngalao = new javax.swing.JButton();
        btncarioca = new javax.swing.JButton();
        btncapu = new javax.swing.JButton();
        btngaroto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnbolo = new javax.swing.JButton();
        btnsalgado = new javax.swing.JButton();
        btnmista = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnagua = new javax.swing.JButton();
        btnvinho = new javax.swing.JButton();
        btncola = new javax.swing.JButton();
        btnsumo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnsoma = new javax.swing.JButton();
        btndiminui = new javax.swing.JButton();
        btnpg = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnprint = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listdescricao = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listquant = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        listpreco = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listtotal = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtdin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txttroco = new javax.swing.JTextField();
        btnquant = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btncafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cafe.gif"))); // NOI18N
        btncafe.setText("<html> <p text-align: center;> Cafe </p> <p text-align: center;>0.60€</p> </html>");
        btncafe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncafe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncafeActionPerformed(evt);
            }
        });

        btndecaf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/descafeinado.gif"))); // NOI18N
        btndecaf.setText("<html> <p text-align: center;> Decaf </p> <p text-align: center;>0.80€</p> </html>");
        btndecaf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndecaf.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndecaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecafActionPerformed(evt);
            }
        });

        btngalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/galao.gif"))); // NOI18N
        btngalao.setText("<html> <p text-align: center;> Galão </p> <p text-align: center;>0.90€</p> </html>");
        btngalao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btngalao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btngalao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngalaoActionPerformed(evt);
            }
        });

        btncarioca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/carioca.gif"))); // NOI18N
        btncarioca.setText("<html>\n<p text-align: center;> Carioca </p>\n<p text-align: center;>0.70€</p>\n</html>");
        btncarioca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncarioca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncarioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariocaActionPerformed(evt);
            }
        });

        btncapu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/capucino.gif"))); // NOI18N
        btncapu.setText("<html> <p text-align: center;> Capucino </p> <p text-align: center;>1.20€</p> </html>");
        btncapu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncapu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncapu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapuActionPerformed(evt);
            }
        });

        btngaroto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/garoto.gif"))); // NOI18N
        btngaroto.setText("<html> <p text-align: center;> Garoto </p> <p text-align: center;>0.60€</p> </html>");
        btngaroto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btngaroto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btngaroto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngarotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btngalao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btncarioca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btncapu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btngaroto)
                    .addComponent(btndecaf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncafe)
                    .addComponent(btncarioca)
                    .addComponent(btndecaf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btngalao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncapu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngaroto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Cafeteria");

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnbolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/bolo.gif"))); // NOI18N
        btnbolo.setText("<html> <p text-align: center;> Bolo </p> <p text-align: center;>1.00€</p> </html>");
        btnbolo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbolo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnboloActionPerformed(evt);
            }
        });

        btnsalgado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/salgado.gif"))); // NOI18N
        btnsalgado.setText("<html>\n<p text-align: center;> Salgado </p>\n<p text-align: center;>1.90€</p>\n</html>");
        btnsalgado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalgado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsalgado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalgadoActionPerformed(evt);
            }
        });

        btnmista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/mista.gif"))); // NOI18N
        btnmista.setText("<html>\n<p text-align: center;> Mista </p>\n<p text-align: center;>1.50€</p>\n</html>");
        btnmista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnmista, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsalgado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsalgado)
                    .addComponent(btnbolo)
                    .addComponent(btnmista))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnagua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/agua.gif"))); // NOI18N
        btnagua.setText("<html>\n<p text-align: center;> Agua </p>\n<p text-align: center;>0.50€</p>\n</html>");
        btnagua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnagua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnagua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaguaActionPerformed(evt);
            }
        });

        btnvinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/vinho.gif"))); // NOI18N
        btnvinho.setText("<html> <p text-align: center;> Vinho </p> <p text-align: center;>1.20€</p> </html>");
        btnvinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnvinho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnvinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvinhoActionPerformed(evt);
            }
        });

        btncola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cola.gif"))); // NOI18N
        btncola.setText("<html>\n<p text-align: center;> Cola </p>\n<p text-align: center;>1.30€</p>\n</html>");
        btncola.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncola.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolaActionPerformed(evt);
            }
        });

        btnsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/sumo.gif"))); // NOI18N
        btnsumo.setText("<html>\n<p text-align: center;> Sumo </p>\n<p text-align: center;>1.60€</p>\n</html>");
        btnsumo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsumo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnagua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnvinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnagua)
                    .addComponent(btnsumo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncola)
                    .addComponent(btnvinho, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Pastelaria");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Bebidas");

        btnsoma.setBackground(new java.awt.Color(204, 204, 204));
        btnsoma.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnsoma.setText("+");
        btnsoma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnsoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsomaActionPerformed(evt);
            }
        });

        btndiminui.setBackground(new java.awt.Color(204, 204, 204));
        btndiminui.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btndiminui.setText("-");
        btndiminui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btndiminui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiminuiActionPerformed(evt);
            }
        });

        btnpg.setBackground(new java.awt.Color(0, 153, 102));
        btnpg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpg.setText("Pagamento");
        btnpg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpgActionPerformed(evt);
            }
        });

        btnlimpar.setBackground(new java.awt.Color(204, 204, 204));
        btnlimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlimpar.setText("Limpar");
        btnlimpar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setName("Dados do Cliente para Faturação"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Dados da Fatura para Impressão");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnprint.setBackground(new java.awt.Color(0, 51, 255));
        btnprint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprint.setForeground(new java.awt.Color(255, 255, 255));
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/printer.png"))); // NOI18N
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel9.setBackground(new java.awt.Color(255, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listdescricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listdescricaoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(listdescricao);

        listquant.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listquant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listquantMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(listquant);

        listpreco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listprecoMouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(listpreco);

        listtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listtotalMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(listtotal);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Pedido");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Descrição");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Qtd");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Preço");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Total");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Total:");

        txttotal.setEditable(false);
        txttotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Numerário:");

        txtdin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Troco:");

        txttroco.setEditable(false);
        txttroco.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnquant.setBackground(new java.awt.Color(255, 102, 102));
        btnquant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnquant.setText("Qtd");
        btnquant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnquant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquantActionPerformed(evt);
            }
        });

        btnremove.setBackground(new java.awt.Color(204, 204, 204));
        btnremove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnremove.setText("Remover");
        btnremove.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnlimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnsoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btndiminui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnpg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnquant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnremove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdin, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(txttroco)))
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnpg, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnremove, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtdin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)))
                        .addGap(31, 31, 31)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnsoma, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnquant, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btndiminui, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    class Imprimir implements Printable{
        public int print(Graphics g, PageFormat f, int pageIndex){
            if (pageIndex==0){
                /* trabalhar a impressão*/
                Font f1=new Font("Tahoma",Font.BOLD,12);
                Font f2=new Font("Tahoma",Font.PLAIN,10);
                Font f3=new Font("Tahoma",Font.PLAIN,8);
                
                g.setFont(f1);
                g.setColor(Color.pink);
                g.drawString("Pastelaria Papa Tudo", 25,25 );
                g.drawString("---------------------------------", 25,30);
                g.setFont(f3);
                g.setColor(Color.gray);
                g.drawString("Rua das Flores, Nº 7",25,  40);
                g.drawString("2810-020 Almada - Telefone: 211222333",25,  50);
                g.drawString("Email: past@gmail.com",25,  60);
                g.drawString("Nif: 567890123",25,  70);
                g.drawLine(25, 80, 200, 80);
                g.drawString("Descrição", 25, 90);
                g.drawString("Qtd.", 65, 90);
                g.drawString("Preço", 80, 90);
                g.drawString("Total", 120, 90);
                g.drawLine(25, 95, 200, 95);
               
                int y=105;
                for(int i=0;i<lista1.getSize();i++){
                    g.drawString(lista1.getElementAt(i).toString(), 25, y);
                    g.drawString(lista2.getElementAt(i).toString(), 65, y);
                    g.drawString(lista3.getElementAt(i).toString(), 80, y);
                    g.drawString(lista4.getElementAt(i).toString(), 120, y);
                    y+=10;
                }
                
                g.drawLine(25, y, 200, y);
                g.drawString("Total:"+txttotal.getText(), 25, y+10);
                g.drawString("Numerário:"+txtdin.getText(), 25, y+20);
                g.drawString("Troco:"+txttroco.getText(), 25, y+30);
                g.drawLine(25, y+40, 200, y+40);
                g.setColor(Color.pink);
                g.drawString("Obrigado. Volte sempre!", 25, y+50);
                return PAGE_EXISTS;
            }
            else{
                return NO_SUCH_PAGE;
            }
                
        }
    }
    
    private void adicionar_Produto(String nome_produto,float preco){
    try{    
        int posicao=listdescricao.getNextMatch(nome_produto, 0, Position.Bias.Forward);
        listquant.setSelectedIndex(posicao);
        int qtd=listquant.getSelectedValue()+1;
        lista2.setElementAt(qtd,posicao);
        
        listtotal.setSelectedIndex(posicao);
        lista4.setElementAt(ft1.format(qtd*preco),posicao);
        
        total+=preco;
        txttotal.setText(ft.format(total));
        
        listdescricao.setSelectedIndex(listquant.getSelectedIndex());
        listpreco.setSelectedIndex(listquant.getSelectedIndex());
        listtotal.setSelectedIndex(listquant.getSelectedIndex());
        
        return;
    }
    catch(Exception e){}    
    // adicionar à lista da descrição
        lista1.addElement(nome_produto);
        listdescricao.setModel(lista1);

        // adicionar à lista da quantidade
        lista2.addElement(1);
        listquant.setModel(lista2);

        // adicionar à lista do preço
        lista3.addElement(preco);
        listpreco.setModel(lista3);
        // adicionar à lista do total
        lista4.addElement(preco);
        listtotal.setModel(lista4);   

        total+=preco;
        txttotal.setText(ft.format(total));       
    
    }
    private void btncafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncafeActionPerformed
        adicionar_Produto("Café",0.6f);

        // adicionar a lista descricao  lista1.addElement(Cafe)
    }//GEN-LAST:event_btncafeActionPerformed

    private void btndecafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndecafActionPerformed
        adicionar_Produto("Decaf",0.8f);

    }//GEN-LAST:event_btndecafActionPerformed

    private void btngalaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngalaoActionPerformed
        adicionar_Produto("Galão",0.9f);

    }//GEN-LAST:event_btngalaoActionPerformed

    private void btncariocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariocaActionPerformed
        adicionar_Produto("Carioca",0.7f);

    }//GEN-LAST:event_btncariocaActionPerformed

    private void btncapuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapuActionPerformed
        adicionar_Produto("Capucino",1.20f);

    }//GEN-LAST:event_btncapuActionPerformed

    private void btngarotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngarotoActionPerformed
        adicionar_Produto("Garoto",0.6f);

    }//GEN-LAST:event_btngarotoActionPerformed

    private void btnboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnboloActionPerformed
        adicionar_Produto("Bolo",1.00f);

    }//GEN-LAST:event_btnboloActionPerformed

    private void btnsalgadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalgadoActionPerformed
        adicionar_Produto("Salgado",1.90f);

    }//GEN-LAST:event_btnsalgadoActionPerformed

    private void btnmistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmistaActionPerformed
        adicionar_Produto("Mista",1.50f);

    }//GEN-LAST:event_btnmistaActionPerformed

    private void btnaguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaguaActionPerformed
        adicionar_Produto("Água",0.5f);

    }//GEN-LAST:event_btnaguaActionPerformed

    private void btnvinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvinhoActionPerformed
        adicionar_Produto("Vinho",1.20f);

    }//GEN-LAST:event_btnvinhoActionPerformed

    private void btncolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolaActionPerformed
        adicionar_Produto("Cola",1.30f);

    }//GEN-LAST:event_btncolaActionPerformed

    private void btnsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumoActionPerformed
        adicionar_Produto("Sumo",1.60f);

    }//GEN-LAST:event_btnsumoActionPerformed

    private void btnsomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsomaActionPerformed
        // verificar se existe algum item selecionado
        if(listdescricao.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(this,
                "Não existem produtos selecionados",
                "Pastelaria Papa Tudo",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        int posicao=listdescricao.getSelectedIndex();

        listquant.setSelectedIndex(posicao);
        int qtd=listquant.getSelectedValue()+1;

        lista2.setElementAt(qtd,posicao);

        listpreco.setSelectedIndex(posicao);
        float prc=listpreco.getSelectedValue();

        listtotal.setSelectedIndex(posicao);
        lista4.setElementAt(ft1.format(qtd*prc),posicao);

        total+=prc;
        txttotal.setText(ft.format(total));

    }//GEN-LAST:event_btnsomaActionPerformed

    private void btndiminuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiminuiActionPerformed
        if(listdescricao.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(this,
                "Não existem produtos a serem removidos",
                "Pastelaria Papa Tudo",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        int posicao=listdescricao.getSelectedIndex();
        listquant.setSelectedIndex(posicao);
        int qtd=listquant.getSelectedValue();
        if(qtd>1){
            lista2.setElementAt(qtd-1,posicao);

            listpreco.setSelectedIndex(posicao);
            float prc=listpreco.getSelectedValue();

            listtotal.setSelectedIndex(posicao);
            lista4.setElementAt(ft1.format(qtd*prc-prc),posicao);

            total-=prc;
            txttotal.setText(ft.format(total));
        }
        else{
            JOptionPane.showMessageDialog(this,
                "A quantidade mínima é 1!",
                "Pastelaria Papa Tudo",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btndiminuiActionPerformed

    private void btnpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpgActionPerformed
        float pg=Float.parseFloat(JOptionPane.showInputDialog(this,"Indique o valor em dinheiro para pagamento:"));
        if (pg<0 || pg<total) {
            JOptionPane.showMessageDialog(this,
                "Valor insuficiente!!",
                "Pastelaria Papa Tudo",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        txtdin.setText(ft.format(pg));
        txttroco.setText(ft.format(pg-total));

    }//GEN-LAST:event_btnpgActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        txttotal.setText("");
        txtdin.setText("");
        txttroco.setText("");
        lista1.clear();
        lista2.clear();
        lista3.clear();
        lista4.clear();
        total=0;

    }//GEN-LAST:event_btnlimparActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // Imprimir o talão
        PrinterJob j=PrinterJob.getPrinterJob();
        j.setPrintable(new Imprimir());
        j.printDialog();

        try{j.print();}
        catch(PrinterException e){}

        ligacaoMySql bd=new ligacaoMySql();
        bd.criarLigacaoMySql();

        try{
            Connection cn=bd.criarLigacaoMySql();
            Statement st =cn.createStatement();
            LocalDateTime sistema=LocalDateTime.now();
            DateTimeFormatter dtf=DateTimeFormatter.ofPattern("dd-MM-yyyy");

            st.executeUpdate("insert into pedidos (data_pedido,total) values('"+dtf.format(sistema)+"','"+total+"')");
            JOptionPane.showMessageDialog(this,
                "Pedido guardado",
                "POS",
                JOptionPane.INFORMATION_MESSAGE);

            //refresh ao pos
            total=0;
            lista1.clear();lista2.clear();lista3.clear();lista4.clear();
            txttotal.setText(" ");txtdin.setText(" ");txttroco.setText(" ");

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,
                "Erro ao guardar o pedido "+e.getMessage(),
                "POS",
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnprintActionPerformed

    private void listdescricaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listdescricaoMouseReleased
        listquant.setSelectedIndex(listdescricao.getSelectedIndex());
        listpreco.setSelectedIndex(listdescricao.getSelectedIndex());
        listtotal.setSelectedIndex(listdescricao.getSelectedIndex());
    }//GEN-LAST:event_listdescricaoMouseReleased

    private void listquantMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listquantMouseReleased
        listdescricao.setSelectedIndex(listquant.getSelectedIndex());
        listpreco.setSelectedIndex(listquant.getSelectedIndex());
        listtotal.setSelectedIndex(listquant.getSelectedIndex());
    }//GEN-LAST:event_listquantMouseReleased

    private void listprecoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listprecoMouseReleased
        listdescricao.setSelectedIndex(listpreco.getSelectedIndex());
        listquant.setSelectedIndex(listpreco.getSelectedIndex());
        listtotal.setSelectedIndex(listpreco.getSelectedIndex());
    }//GEN-LAST:event_listprecoMouseReleased

    private void listtotalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listtotalMouseReleased
        listdescricao.setSelectedIndex(listtotal.getSelectedIndex());
        listpreco.setSelectedIndex(listtotal.getSelectedIndex());
        listquant.setSelectedIndex(listtotal.getSelectedIndex());
    }//GEN-LAST:event_listtotalMouseReleased

    private void btnquantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquantActionPerformed
        if(listdescricao.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(this,
                "Não existem produtos selecionados",
                "Pastelaria Papa Tudo",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        int posicao=listdescricao.getSelectedIndex();
        int qtd = listquant.getSelectedValue();
        float prc = listpreco.getSelectedValue();
        total -= (qtd*prc);
        qtd = Integer.parseInt(JOptionPane.showInputDialog(this, "Indique a quantidade desejada:",
            "Pastelaria Papa Tudo",JOptionPane.QUESTION_MESSAGE));

    if(qtd<=0){
        qtd = Integer.parseInt(JOptionPane.showInputDialog(this, "Indique novamente a quantidade desejada:",
            "Pastelaria Papa Tudo",JOptionPane.QUESTION_MESSAGE));
    }
    lista2.setElementAt(qtd,posicao);
    listpreco.setSelectedIndex(posicao);
    listtotal.setSelectedIndex(posicao);
    lista4.setElementAt(ft1.format(qtd*prc),posicao);
    total+= (qtd*prc);
    txttotal.setText(ft.format(total));
    }//GEN-LAST:event_btnquantActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        if(listdescricao.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(this,
                "Não existem produtos selecionados",
                "Pastelaria Papa Tudo",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        int posicao=listdescricao.getSelectedIndex();
        int qtd = listquant.getSelectedValue();
        float prc = listpreco.getSelectedValue();
        lista1.removeElementAt(posicao);
        lista2.removeElementAt(posicao);
        lista3.removeElementAt(posicao);
        lista4.removeElementAt(posicao);
        listdescricao.setModel(lista1);
        listquant.setModel(lista2);
        listpreco.setModel(lista3);
        listtotal.setModel(lista4);
        total -= (qtd*prc);
        txttotal.setText(ft.format(total));
    }//GEN-LAST:event_btnremoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pastel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pastel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pastel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pastel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pastel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagua;
    private javax.swing.JButton btnbolo;
    private javax.swing.JButton btncafe;
    private javax.swing.JButton btncapu;
    private javax.swing.JButton btncarioca;
    private javax.swing.JButton btncola;
    private javax.swing.JButton btndecaf;
    private javax.swing.JButton btndiminui;
    private javax.swing.JButton btngalao;
    private javax.swing.JButton btngaroto;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnmista;
    private javax.swing.JButton btnpg;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnquant;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnsalgado;
    private javax.swing.JButton btnsoma;
    private javax.swing.JButton btnsumo;
    private javax.swing.JButton btnvinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listdescricao;
    private javax.swing.JList<Float> listpreco;
    private javax.swing.JList<Integer> listquant;
    private javax.swing.JList<Float> listtotal;
    private javax.swing.JTextField txtdin;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttroco;
    // End of variables declaration//GEN-END:variables
}
