/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javafinal2;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.text.Position;

/**
 *
 * @author Andrea Silva
 */
public class Info extends javax.swing.JFrame {

    DefaultListModel lista1=new DefaultListModel();
    float total=0;
    DecimalFormat ft= new DecimalFormat("#,##0.00€");
    
    
    
    
    public Info() {
        initComponents();
        
        lblboard.setVisible(false);
        lblfonte.setVisible(false);
        lblram.setVisible(false);
        lblcaixa.setVisible(false);
        lblrato.setVisible(false);
        lblgrafica.setVisible(false);
        lblprocessa.setVisible(false);
        lbldisco.setVisible(false);
        lblteclado.setVisible(false);
        
        
        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatarDate = new SimpleDateFormat("dd-MM-yyyy");
        lbldata.setText(formatarDate.format(data));
        
        getContentPane().setBackground(new Color(153, 204, 255));
    }
    
    class Imprimir implements Printable{
        public int print(Graphics g, PageFormat f, int pageIndex){
            if (pageIndex==0){
                /* trabalhar a impressão*/
                Font f1=new Font("Tahoma",Font.BOLD,12);
                Font f2=new Font("Tahoma",Font.PLAIN,10);
                Font f3=new Font("Tahoma",Font.PLAIN,8);
                
                g.setFont(f1);
                g.setColor(Color.blue);
                g.drawString("---------------------------------", 25,40);
                g.drawString("Componentes Info", 25,50 );
                g.drawString("---------------------------------", 25,60);
                g.setFont(f3);
                g.setColor(Color.gray);
                g.drawLine(25, 80, 200, 80);
                g.drawString("Produto", 25, 90);
                g.drawLine(25, 95, 200, 95);
                
               
                int y=105;
                for(int i=0;i<lista1.getSize();i++){
                    g.drawString(lista1.getElementAt(i).toString(), 25, y);
                    
                    
                    y+=10;
                }
                
                g.drawLine(25, y, 200, y);
                g.drawString("Total:", 25, y+10);
                g.drawString(txttotal.getText(), 47, y+10); 
                g.drawString("Data:", 25, y+20);
                g.drawString(lbldata.getText(), 45, y+20);
                g.drawLine(25, y+25, 200, y+25);
                g.setColor(Color.blue);
                g.setFont(f2);
                g.drawString("Obrigado por nos escolher.Volte sempre!", 25, y+50);
                return PAGE_EXISTS;
            }
            else{
                return NO_SUCH_PAGE;
            }
               
        }
        
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cboxmother = new javax.swing.JCheckBox();
        cboxfonte = new javax.swing.JCheckBox();
        cboxram = new javax.swing.JCheckBox();
        cboxcaixa = new javax.swing.JCheckBox();
        cboxrato = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        cboxgrafica = new javax.swing.JCheckBox();
        cboxprocessador = new javax.swing.JCheckBox();
        cboxdisco = new javax.swing.JCheckBox();
        cboxteclado = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listcomponentes = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btnimprimir = new javax.swing.JButton();
        btnnova = new javax.swing.JButton();
        btnguarda = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblboard = new javax.swing.JLabel();
        lblfonte = new javax.swing.JLabel();
        lblram = new javax.swing.JLabel();
        lblcaixa = new javax.swing.JLabel();
        lblrato = new javax.swing.JLabel();
        lblgrafica = new javax.swing.JLabel();
        lblprocessa = new javax.swing.JLabel();
        lbldisco = new javax.swing.JLabel();
        lblteclado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbldata = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulação de Montagem");
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Componentes");

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cboxmother.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboxmother.setText("Motherboard 100€");
        cboxmother.setEnabled(false);
        cboxmother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxmotherActionPerformed(evt);
            }
        });

        cboxfonte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboxfonte.setText("Fonte 80€");
        cboxfonte.setActionCommand("Fonte");
        cboxfonte.setEnabled(false);
        cboxfonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxfonteActionPerformed(evt);
            }
        });

        cboxram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboxram.setText("Memoria 100€");
        cboxram.setEnabled(false);
        cboxram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxramActionPerformed(evt);
            }
        });

        cboxcaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboxcaixa.setText("Caixa 50€");
        cboxcaixa.setEnabled(false);
        cboxcaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxcaixaActionPerformed(evt);
            }
        });

        cboxrato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboxrato.setText("Rato 100€");
        cboxrato.setEnabled(false);
        cboxrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboxmother)
                .addGap(34, 34, 34)
                .addComponent(cboxfonte, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(cboxram)
                .addGap(18, 18, 18)
                .addComponent(cboxcaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboxrato)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxmother)
                    .addComponent(cboxfonte)
                    .addComponent(cboxram)
                    .addComponent(cboxcaixa)
                    .addComponent(cboxrato))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cboxgrafica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboxgrafica.setText("Grafica 300€");
        cboxgrafica.setEnabled(false);
        cboxgrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxgraficaActionPerformed(evt);
            }
        });

        cboxprocessador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboxprocessador.setText("Processador 300€");
        cboxprocessador.setActionCommand("Fonte");
        cboxprocessador.setEnabled(false);
        cboxprocessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxprocessadorActionPerformed(evt);
            }
        });

        cboxdisco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboxdisco.setText("Disco 200€");
        cboxdisco.setEnabled(false);
        cboxdisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxdiscoActionPerformed(evt);
            }
        });

        cboxteclado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboxteclado.setText("Teclado 100€");
        cboxteclado.setEnabled(false);
        cboxteclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxtecladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboxgrafica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboxprocessador)
                .addGap(28, 28, 28)
                .addComponent(cboxdisco)
                .addGap(33, 33, 33)
                .addComponent(cboxteclado)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxgrafica)
                    .addComponent(cboxprocessador)
                    .addComponent(cboxdisco)
                    .addComponent(cboxteclado))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        listcomponentes.setBackground(new java.awt.Color(153, 204, 255));
        listcomponentes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listcomponentes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jScrollPane1.setViewportView(listcomponentes);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Configurações");

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Total");

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txttotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnimprimir.setBackground(new java.awt.Color(51, 153, 255));
        btnimprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnimprimir.setText("Imprimir");
        btnimprimir.setEnabled(false);
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        btnnova.setBackground(new java.awt.Color(51, 153, 255));
        btnnova.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnova.setText("Nova Configuração");
        btnnova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovaActionPerformed(evt);
            }
        });

        btnguarda.setBackground(new java.awt.Color(51, 153, 255));
        btnguarda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguarda.setText("Guarda Configuração");
        btnguarda.setEnabled(false);
        btnguarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardaActionPerformed(evt);
            }
        });

        btnsair.setBackground(new java.awt.Color(153, 255, 102));
        btnsair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsair.setText("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        btnlimpar.setBackground(new java.awt.Color(153, 255, 102));
        btnlimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnova, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguarda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnimprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguarda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnova, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblboard.setBackground(new java.awt.Color(51, 153, 255));
        lblboard.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblboard.setText("Board");
        lblboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblboard.setOpaque(true);

        lblfonte.setBackground(new java.awt.Color(153, 0, 153));
        lblfonte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblfonte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfonte.setText("Fonte");
        lblfonte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblfonte.setOpaque(true);

        lblram.setBackground(new java.awt.Color(0, 51, 204));
        lblram.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblram.setText("Ram");
        lblram.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblram.setOpaque(true);

        lblcaixa.setBackground(new java.awt.Color(153, 0, 153));
        lblcaixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcaixa.setText("Caixa");
        lblcaixa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblcaixa.setOpaque(true);

        lblrato.setBackground(new java.awt.Color(204, 102, 255));
        lblrato.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblrato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblrato.setText("Rato");
        lblrato.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblrato.setOpaque(true);

        lblgrafica.setBackground(new java.awt.Color(51, 153, 255));
        lblgrafica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblgrafica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblgrafica.setText("Gráfica");
        lblgrafica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblgrafica.setOpaque(true);

        lblprocessa.setBackground(new java.awt.Color(51, 153, 255));
        lblprocessa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblprocessa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblprocessa.setText("Process");
        lblprocessa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblprocessa.setOpaque(true);

        lbldisco.setBackground(new java.awt.Color(0, 51, 204));
        lbldisco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbldisco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldisco.setText("Disco");
        lbldisco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbldisco.setOpaque(true);

        lblteclado.setBackground(new java.awt.Color(204, 102, 255));
        lblteclado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblteclado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblteclado.setText("Teclado");
        lblteclado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblteclado.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblboard, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblfonte, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblram, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblcaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblrato, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblgrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblprocessa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldisco, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblteclado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblboard, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfonte, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblram, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrato, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprocessa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldisco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblteclado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Data");

        lbldata.setBackground(new java.awt.Color(153, 204, 255));
        lbldata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldata.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbldata.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbldata, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(lbldata, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsairActionPerformed

    private void btnguardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardaActionPerformed
        ligacaoMySql bd=new ligacaoMySql();
        bd.criarLigacaoMySql();

        try{
            Connection cn=bd.criarLigacaoMySql();
            Statement st =cn.createStatement();
            LocalDateTime sistema=LocalDateTime.now();
            DateTimeFormatter dtf=DateTimeFormatter.ofPattern("dd-MM-yyyy");
            int max = lista1.getSize();
            for (int posicao = 0;posicao < max;posicao++){
                st.executeUpdate("insert into tab_componentes (Componentes,Data) "
                        + "values('"+lista1.getElementAt(posicao)+ "','"+dtf.format(sistema)+"')");
                JOptionPane.showMessageDialog(this,
                    "Dados guardados",
                    "Componentes Info",
                    JOptionPane.INFORMATION_MESSAGE);
            }

            lista1.clear();

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,
                "Erro ao guardar os dados! "+e.getMessage(),
                "Componentes Info",
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnguardaActionPerformed

    private void btnnovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovaActionPerformed
        btnguarda.setEnabled(true);
        btnimprimir.setEnabled(true);
        cboxmother.setEnabled(true);
        cboxcaixa.setEnabled(true);
        cboxfonte.setEnabled(true);
        cboxram.setEnabled(true);
        cboxrato.setEnabled(true);
        cboxprocessador.setEnabled(true);
        cboxgrafica.setEnabled(true);
        cboxdisco.setEnabled(true);
        cboxteclado.setEnabled(true);
        
    }//GEN-LAST:event_btnnovaActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        PrinterJob j=PrinterJob.getPrinterJob();
        j.setPrintable(new Imprimir());
        j.printDialog();

        try{j.print();}
        catch(PrinterException e){}
        
    }//GEN-LAST:event_btnimprimirActionPerformed
    private void adicionar_Componente(String nome_componente,float valor){
    try{    
        int posicao=listcomponentes.getNextMatch(nome_componente, 0, Position.Bias.Forward);
        listcomponentes.setSelectedIndex(posicao);
        lista1.addElement(nome_componente);
        total+=valor;
        txttotal.setText(ft.format(total));
        listcomponentes.setSelectedIndex(listcomponentes.getSelectedIndex());
    return;
    }
    catch(Exception e){}    
        lista1.addElement(nome_componente);
        listcomponentes.setModel(lista1);
        total+=valor;
        txttotal.setText(ft.format(total));       
    
    }
    
    private void remover_Componente(String nome_componente,float valor){
     try{    
        int posicao=listcomponentes.getNextMatch(nome_componente, 0, Position.Bias.Forward);
        listcomponentes.setSelectedIndex(posicao);
        lista1.removeElement(nome_componente);
        total-=valor;
        txttotal.setText(ft.format(total));
        listcomponentes.setSelectedIndex(listcomponentes.getSelectedIndex());
    return;
    }
    catch(Exception e){}    
        lista1.removeElement(nome_componente);
        listcomponentes.setModel(lista1);
        total-=valor;
        txttotal.setText(ft.format(total));       
       
        
    }
    private void cboxmotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxmotherActionPerformed
        lblboard.setVisible(true);
        
        if(cboxmother.isSelected()){
            lblboard.setVisible(true);
            adicionar_Componente("Motherboard-100€",100f);
            
        }
        else{
            lblboard.setVisible(false);
            remover_Componente("Motherboard-100€",100f);
        }
         
        
    }//GEN-LAST:event_cboxmotherActionPerformed

    private void cboxcaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxcaixaActionPerformed
        lblcaixa.setVisible(true);
        
        if(cboxcaixa.isSelected()){
            lblcaixa.setVisible(true);
            adicionar_Componente("Caixa-50€",50f);
        }
        else{
            lblcaixa.setVisible(false);
            remover_Componente("Caixa-50€",50f);
    }//GEN-LAST:event_cboxcaixaActionPerformed
       
    }
    
    private void cboxfonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxfonteActionPerformed
        lblfonte.setVisible(true);
        
        if(cboxfonte.isSelected()){
            lblfonte.setVisible(true);
            adicionar_Componente("Fonte-80€",80f);
        }
        else{
            lblfonte.setVisible(false);
            remover_Componente("Fonte-80€",80f);
    }//GEN-LAST:event_cboxfonteActionPerformed
        
    
    }
    
    private void cboxramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxramActionPerformed
        lblram.setVisible(true);
        
        if(cboxram.isSelected()){
            lblram.setVisible(true);
            adicionar_Componente("Memória-100€",100f);
            
        }
        else{
            lblram.setVisible(false);
            remover_Componente("Memória-100€",100f);
    }                                       
        
    }//GEN-LAST:event_cboxramActionPerformed

    private void cboxratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxratoActionPerformed
        lblrato.setVisible(true);
        
        if(cboxrato.isSelected()){
            lblrato.setVisible(true);
            adicionar_Componente("Rato-100€",100f);
        }
        else{
            lblrato.setVisible(false);
            remover_Componente("Rato-100€",100f);
    }
        
    }//GEN-LAST:event_cboxratoActionPerformed

    private void cboxgraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxgraficaActionPerformed
        lblgrafica.setVisible(true);
        
        if(cboxgrafica.isSelected()){
            lblgrafica.setVisible(true);
            adicionar_Componente("Gráfica-300€",300f);
        }
        else{
            lblgrafica.setVisible(false);
            remover_Componente("Gráfica-300€",300f);
    }
        
    }//GEN-LAST:event_cboxgraficaActionPerformed

    private void cboxprocessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxprocessadorActionPerformed
        lblprocessa.setVisible(true);
        
        if(cboxprocessador.isSelected()){
            lblprocessa.setVisible(true);
            adicionar_Componente("Processador-300€",300f);
        }
        else{
            lblprocessa.setVisible(false);
            remover_Componente("Processador-300€",300f);
        }
        
    }//GEN-LAST:event_cboxprocessadorActionPerformed

    private void cboxdiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxdiscoActionPerformed
        lbldisco.setVisible(true);
        
        if(cboxdisco.isSelected()){
            lbldisco.setVisible(true);
            adicionar_Componente("Disco-200€",200f);
        }
        else{
            lbldisco.setVisible(false);
            remover_Componente("Disco-200€",200f);
    }  
        
    }//GEN-LAST:event_cboxdiscoActionPerformed

    private void cboxtecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxtecladoActionPerformed
        lblteclado.setVisible(true);
        
        if(cboxteclado.isSelected()){
            lblteclado.setVisible(true);
            adicionar_Componente("Teclado-100€",100f);
        }
        else{
            lblteclado.setVisible(false);
            remover_Componente("Teclado-100€",100f);
    }  
        
    }//GEN-LAST:event_cboxtecladoActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        btnguarda.setEnabled(false);
        btnimprimir.setEnabled(false);
        cboxmother.setEnabled(false);
        cboxmother.setSelected(false);
        cboxcaixa.setEnabled(false);
        cboxcaixa.setSelected(false);
        cboxfonte.setEnabled(false);
        cboxfonte.setSelected(false);
        cboxram.setEnabled(false);
        cboxram.setSelected(false);
        cboxrato.setEnabled(false);
        cboxrato.setSelected(false);
        cboxprocessador.setEnabled(false);
        cboxprocessador.setSelected(false);
        cboxgrafica.setEnabled(false);
        cboxgrafica.setSelected(false);
        cboxdisco.setEnabled(false);
        cboxdisco.setSelected(false);
        cboxteclado.setEnabled(false);
        cboxteclado.setSelected(false);
        txttotal.setText("");
        lista1.clear();
        lblboard.setVisible(false);
        lblfonte.setVisible(false);
        lblram.setVisible(false);
        lblcaixa.setVisible(false);
        lblrato.setVisible(false);
        lblgrafica.setVisible(false);
        lblprocessa.setVisible(false);
        lbldisco.setVisible(false);
        lblteclado.setVisible(false);
        total=0;
    }//GEN-LAST:event_btnlimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguarda;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnnova;
    private javax.swing.JButton btnsair;
    private javax.swing.JCheckBox cboxcaixa;
    private javax.swing.JCheckBox cboxdisco;
    private javax.swing.JCheckBox cboxfonte;
    private javax.swing.JCheckBox cboxgrafica;
    private javax.swing.JCheckBox cboxmother;
    private javax.swing.JCheckBox cboxprocessador;
    private javax.swing.JCheckBox cboxram;
    private javax.swing.JCheckBox cboxrato;
    private javax.swing.JCheckBox cboxteclado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblboard;
    private javax.swing.JLabel lblcaixa;
    private javax.swing.JLabel lbldata;
    private javax.swing.JLabel lbldisco;
    private javax.swing.JLabel lblfonte;
    private javax.swing.JLabel lblgrafica;
    private javax.swing.JLabel lblprocessa;
    private javax.swing.JLabel lblram;
    private javax.swing.JLabel lblrato;
    private javax.swing.JLabel lblteclado;
    private javax.swing.JList<String> listcomponentes;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
